version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.15
    container_name: apm-server
    ports:
      - "8200:8200"
    command: >
      apm-server -e
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.rum.enabled=true
        -E apm-server.rum.allow_origins=["*"]
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
        -E setup.template.enabled=true
        -E setup.dashboards.enabled=true
        -E setup.kibana.host=kibana:5601
        -E logging.level=info
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elastic

volumes:
  esdata:

networks:
  elastic:
    driver: bridge